### 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [ ]:
import tensorflow as tf

# Creating a scalar
scalar = tf.constant(3)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
# Creating a vector
vector = tf.constant([7, 7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Creating a matrix
matrix = tf.constant([[2, 4, 6],
                      [8, 10, 12]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)>

In [ ]:
# Creating a tensor
tensor = tf.constant([[[2, 6, 6],
                       [8, 10, 12]],
                      [[14, 16, 18],
                      [20, 22, 24]]], dtype = tf.float16)
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=float16, numpy=
array([[[ 2.,  6.,  6.],
        [ 8., 10., 12.]],

       [[14., 16., 18.],
        [20., 22., 24.]]], dtype=float16)>

### 2. Find the shape, rank and size of the tensors you created in 1.


In [ ]:
import pandas as pd
import numpy as np
shape_rank_size = [["scalar", scalar.shape, scalar.ndim, scalar.dtype],
                   ["vector", vector.shape, vector.ndim, vector.dtype],
                   ["matrix", matrix.shape, matrix.ndim, matrix.dtype],
                   ["tensor", tensor.shape, tensor.ndim, tensor.dtype]]
pd.DataFrame(shape_rank_size, columns= ["Object", "Shape", "Rank", "DataType"])

Object      Shape  Rank            DataType
0  scalar         ()     0    <dtype: 'int32'>
1  vector        (2)     1    <dtype: 'int32'>
2  matrix     (2, 3)     2    <dtype: 'int32'>
3  tensor  (2, 2, 3)     3  <dtype: 'float16'>

### 3. Create two tensors containing random values between 0 and 1 with shape [5, 300].


In [ ]:
# Creating tensor A with randm values between 0 and 1 with shape [5, 300]
# A = tf.random.Generator.from_seed(42)
A = tf.random.uniform(shape= (5, 300), minval = 0, maxval = 1, seed=42 )
A

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.95227146, 0.67740774, 0.79531825, ..., 0.24914539, 0.79465246,
        0.37908268],
       [0.01775956, 0.93868697, 0.0599196 , ..., 0.13451016, 0.8998395 ,
        0.60149   ],
       [0.67270994, 0.7580242 , 0.61660326, ..., 0.9782629 , 0.05106342,
        0.7171614 ],
       [0.34828532, 0.12214732, 0.8777071 , ..., 0.40781522, 0.983263  ,
        0.7197592 ],
       [0.6248894 , 0.45999432, 0.35873818, ..., 0.09566212, 0.4957862 ,
        0.5949969 ]], dtype=float32)>

In [ ]:
# Creating tensor A with randm values between 0 and 1 with shape [5, 300]
B = tf.random.uniform(shape=(5, 300), minval=0, maxval=1, seed=777)
B

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.7995087 , 0.57497156, 0.5577297 , ..., 0.49750817, 0.7295283 ,
        0.3265257 ],
       [0.52371764, 0.75832415, 0.647809  , ..., 0.6840844 , 0.80933464,
        0.15436077],
       [0.6644192 , 0.53631806, 0.39372826, ..., 0.3741125 , 0.19792736,
        0.6053889 ],
       [0.8759577 , 0.29860675, 0.7204925 , ..., 0.98021626, 0.14452982,
        0.01579094],
       [0.71805155, 0.85225034, 0.5263133 , ..., 0.46282887, 0.8512862 ,
        0.88803065]], dtype=float32)>

### 4. Multiply the two tensors you created in 3 using matrix multiplication.


In [ ]:
# multiplying tensors A and B using matrix multiplication
tf.matmul(A, tf.reshape(B, shape= (300, 5)))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[69.5624  , 73.102745, 78.15531 , 76.125565, 74.57991 ],
       [67.82406 , 71.9445  , 74.11547 , 75.10167 , 73.58528 ],
       [70.57028 , 75.02623 , 74.70934 , 74.92985 , 72.841675],
       [67.28814 , 73.81627 , 74.97514 , 73.74068 , 73.66307 ],
       [69.85878 , 75.502106, 79.29994 , 79.352585, 76.39781 ]],
      dtype=float32)>

### 5. Multiply the two tensors you created in 3 using dot product.

In [ ]:
# Multiplying Tensors A and B using dot product
tf.tensordot(tf.reshape(A, shape= (300, 5)), B, axes= 1)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[2.648338  , 2.119082  , 2.0781171 , ..., 2.195821  , 1.9147812 ,
        1.3315808 ],
       [1.4917802 , 1.2820452 , 1.1403937 , ..., 1.1483032 , 1.2978797 ,
        0.9516104 ],
       [1.6953672 , 1.3983759 , 1.4325956 , ..., 1.5887883 , 1.1054387 ,
        0.71473897],
       ...,
       [2.286592  , 1.8162613 , 1.8144557 , ..., 1.9418695 , 1.5599052 ,
        1.0835025 ],
       [1.1180009 , 0.9569379 , 0.8139095 , ..., 0.84253097, 0.7978819 ,
        0.8750666 ],
       [1.3473765 , 1.0415138 , 1.0258417 , ..., 1.0893776 , 1.0096844 ,
        0.76168925]], dtype=float32)>

### 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].


In [44]:
# Creating a tensor with random values between 0 and 1 with shape [224, 224, 3]
C = tf.random.uniform(shape=(224, 224, 3), minval= 0, maxval= 1, seed= 777)
C

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.52045953, 0.852353  , 0.08531857],
        [0.2666645 , 0.40954292, 0.48927402],
        [0.3335383 , 0.57923055, 0.21743858],
        ...,
        [0.07909203, 0.10837257, 0.12952459],
        [0.6955079 , 0.71155906, 0.42240012],
        [0.9529835 , 0.03702223, 0.626003  ]],

       [[0.5530375 , 0.8974174 , 0.20934534],
        [0.70460474, 0.8527926 , 0.8807167 ],
        [0.14445186, 0.72266674, 0.01565289],
        ...,
        [0.6110761 , 0.54638267, 0.01683044],
        [0.19342732, 0.71798694, 0.5907297 ],
        [0.54984426, 0.18728912, 0.9663471 ]],

       [[0.18694448, 0.580495  , 0.3968414 ],
        [0.15126681, 0.5604578 , 0.63776875],
        [0.44198072, 0.44918537, 0.7949021 ],
        ...,
        [0.4428699 , 0.8467897 , 0.89285123],
        [0.9460956 , 0.54709303, 0.6271851 ],
        [0.5514711 , 0.9338156 , 0.37711513]],

       ...,

       [[0.70317817, 0.34837472, 0.46117687],
        [0.59

### 7. Find the min and max values of the tensor you created in 6.


In [49]:
# Maximum value of tensor C
tf.reduce_max(C)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9999963>

In [50]:
# Minimum value of tensor C
tf.reduce_min(C)

<tf.Tensor: shape=(), dtype=float32, numpy=1.9073486e-06>

In [55]:
# positional maximum of tensor C
tf.argmax(C)

<tf.Tensor: shape=(224, 3), dtype=int64, numpy=
array([[  9, 157,  94],
       [209, 115, 215],
       [ 80, 125,  75],
       [ 72, 101,  95],
       [203, 109,   2],
       [166, 213,  46],
       [ 81, 189, 179],
       [  4, 175,  87],
       [ 19,  23, 153],
       [ 83,  36,  48],
       [ 68, 160, 186],
       [138,  62, 115],
       [ 88, 193, 223],
       [151,  84,  76],
       [142, 110,  73],
       [ 85, 145,  60],
       [ 89, 187,   4],
       [ 41, 176,  90],
       [ 53,  94,  36],
       [217,  76,  47],
       [196, 132,   1],
       [ 40, 190, 149],
       [  2,  56, 222],
       [184, 209,  63],
       [147,  90, 100],
       [ 51, 145, 207],
       [213,  19,  52],
       [164,  27, 191],
       [150, 154,  83],
       [221, 204, 221],
       [141,  62, 182],
       [214, 148, 147],
       [162, 134,  60],
       [ 62, 108, 207],
       [157, 211, 202],
       [176, 190,  59],
       [103, 212,  90],
       [ 78,  72, 212],
       [133,  48,  48],
       [ 26, 172

### 8. Create a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].


In [56]:
# Creating a tensor with random values of shape [1, 224, 224, 3]
D = tf.random.uniform(shape= (1, 224, 224, 3), minval=0, maxval=1, seed=777)

# Squeeze the tensor to change the shape to [224, 224, 3]
D_squeezed = tf.squeeze(D)

# Print shape
D.shape, D_squeezed.shape

(TensorShape([1, 224, 224, 3]), TensorShape([224, 224, 3]))

### 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.


In [81]:
# Creating tensor E with shape [10]
E = tf.range(0, 10)
tf.random.set_seed(777)
E_shuffled = tf.random.shuffle(E)
E, E.shape, E_shuffled, E_shuffled.shape

(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>,
 TensorShape([10]),
 <tf.Tensor: shape=(10,), dtype=int32, numpy=array([5, 4, 1, 8, 3, 6, 9, 2, 0, 7], dtype=int32)>,
 TensorShape([10]))

In [82]:
# finding the index which has the maximum value in E_shuffled
tf.argmax(E_shuffled)

<tf.Tensor: shape=(), dtype=int64, numpy=6>

In [83]:
# finding the index which has the minimum value in E_shuffled
tf.argmin(E_shuffled)

<tf.Tensor: shape=(), dtype=int64, numpy=8>

### 10. One-hot encode the tensor you created in 9.

In [85]:
# One-hot encode tensor E_shuffled
tf.one_hot(E_shuffled, 10) # I used 10 for the depth because tensor E has 10 values

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]], dtype=float32)>